using System;

namespace JoyCraftSDK.Utilities
{
	[Serializable]
	public enum AnalyticsEvent
	{
		session_start = 0,
		session_end = 1,
		session_pause = 2,
		session_focus = 3,
		tutorial_start = 4,
		tutorial_finish_step = 5,
		tutorial_complete = 6,
		tutorial = 7,
		game_start = 8,
		level_start = 9,
		game_over = 10,
		level_exit = 11,
		level_end = 12,
		feature_unlock = 13,
		booster_clicked = 14,
		booster_bought = 15,
		booster_used = 16,
		out_game = 17,
		bi_resource_event = 18,
		resource_earn = 19,
		resource_spend = 20,
		screen_view = 21,
		screen_show = 22,
		screen_exit = 23,
		button_try_click = 24,
		button_click_success = 25,
		bgm_change = 26,
		sfx_change = 27,
		haptic_change = 28,
		login_day = 29,
		loading_start = 30,
		loading_time = 31,
		loading_finish = 32,
		error_event = 33,
		ad_request = 34,
		ad_impression = 35,
		ad_click = 36,
		ad_complete = 37,
		ad_reward_claimed = 38,
		bi_ad_value = 39,
		bi_business_event = 40,
		iap_show = 41,
		iap_close = 42,
		iap_click = 43,
		iap_purchase_success = 44,
		iap_purchase_failed = 45,
		noti_open = 46
	}
}
